// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication11.Data;

namespace WebApplication11.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication11.Model.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PermissionID");

                    b.Property<int>("RoleID");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("RoleID");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("WebApplication11.Model.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PermissionName");

                    b.HasKey("ID");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("WebApplication11.Model.Role", b =>
                {
                    b.Property<int>("RoleID");

                    b.Property<string>("Title");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("WebApplication11.Model.RoleAssignment", b =>
                {
                    b.Property<int>("RoleID");

                    b.Property<int>("UserID");

                    b.HasKey("RoleID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("RoleAssignment");
                });

            modelBuilder.Entity("WebApplication11.Model.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstMidName");

                    b.Property<DateTime>("HireDate");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebApplication11.Model.Enrollment", b =>
                {
                    b.HasOne("WebApplication11.Model.Permission", "Permission")
                        .WithMany("Enrollments")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApplication11.Model.Role", "Role")
                        .WithMany("Enrollments")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApplication11.Model.RoleAssignment", b =>
                {
                    b.HasOne("WebApplication11.Model.Role", "Role")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApplication11.Model.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
